refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  main_appender:
    kind: rolling_file
    path: log/main.log
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} | {({l}):5.5} | {f}:{L} — {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 30 mb
      roller:
        kind: fixed_window
        pattern: logs/main_{}.gz
        count: 5
        base: 1
root:
  level: info
  appenders:
    - stdout
    - main_appender
